//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConfectioneryChain_V5Entities : DbContext
    {
        public ConfectioneryChain_V5Entities()
            : base("name=ConfectioneryChain_V5Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuyGood> BuyGoods { get; set; }
        public virtual DbSet<Confectionery> Confectioneries { get; set; }
        public virtual DbSet<DistributionOfEmployee> DistributionOfEmployees { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FilingTheWarehouseConfectionery> FilingTheWarehouseConfectioneries { get; set; }
        public virtual DbSet<GoodsInBuy> GoodsInBuys { get; set; }
        public virtual DbSet<StaffWorkSchedule> StaffWorkSchedules { get; set; }
        public virtual DbSet<Good> Goods { get; set; }
        public virtual DbSet<OrderIssueOption> OrderIssueOptions { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<TypeOfGood> TypeOfGoods { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<Check> Checks { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<PriceList> PriceLists { get; set; }
        public virtual DbSet<PriceListRecipe> PriceListRecipes { get; set; }
        public virtual DbSet<RecipesInOrder> RecipesInOrders { get; set; }
        public virtual DbSet<ToppingInOrder> ToppingInOrders { get; set; }
        public virtual DbSet<HierararchyInRecipe> HierararchyInRecipes { get; set; }
        public virtual DbSet<ItemInRecipe> ItemInRecipes { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<ToppingInRecipe> ToppingInRecipes { get; set; }
        public virtual DbSet<FilingTheWarehouseShop> FilingTheWarehouseShops { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
    }
}
