//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Confectionery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Confectionery()
        {
            this.DistributionOfEmployees = new HashSet<DistributionOfEmployee>();
            this.FilingTheWarehouseConfectioneries = new HashSet<FilingTheWarehouseConfectionery>();
            this.Orders = new HashSet<Order>();
            this.PriceLists = new HashSet<PriceList>();
        }
    
        public int IDConfectionery { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public decimal RentPricel { get; set; }
        public System.TimeSpan BeginWork { get; set; }
        public System.TimeSpan EndWork { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistributionOfEmployee> DistributionOfEmployees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilingTheWarehouseConfectionery> FilingTheWarehouseConfectioneries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceList> PriceLists { get; set; }



        public override string ToString()
        {
            return $"[{Name}]";
        }
    }
}
