//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilingTheWarehouseShop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FilingTheWarehouseShop()
        {
            this.GoodsInBuys = new HashSet<GoodsInBuy>();
        }
    
        public int ShopID { get; set; }
        public int GoodsID { get; set; }
        public decimal Count { get; set; }
        public Nullable<decimal> PriceBuy { get; set; }
        public Nullable<decimal> PriceSell { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsInBuy> GoodsInBuys { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
