//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int OrderID { get; set; }
        public string Address { get; set; }
        public bool MarkBuyerSignature { get; set; }
        public string ClaimText { get; set; }
        public bool ReturnMARK { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
