//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemInRecipe()
        {
            this.ItemInRecipe1 = new HashSet<ItemInRecipe>();
            this.RecipesInOrders = new HashSet<RecipesInOrder>();
        }
    
        public int IDItemInRecipe { get; set; }
        public Nullable<int> ItemInRecipeID { get; set; }
        public int RecipeID { get; set; }
        public int Hierarchy { get; set; }
        public Nullable<int> GoodsID { get; set; }
        public decimal Count { get; set; }
        public decimal PercentageOfInfluenceOnTaste { get; set; }
    
        public virtual Good Good { get; set; }
        public virtual HierararchyInRecipe HierararchyInRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInRecipe> ItemInRecipe1 { get; set; }
        public virtual ItemInRecipe ItemInRecipe2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipesInOrder> RecipesInOrders { get; set; }
    }
}
