//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.RecipesInOrders = new HashSet<RecipesInOrder>();
        }
    
        public int IDOrder { get; set; }
        public int ConfectioneryID { get; set; }
        public decimal CustomerPhone { get; set; }
        public string OrderIssueOptionChar { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Confectionery Confectionery { get; set; }
        public virtual OrderIssueOption OrderIssueOption { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipesInOrder> RecipesInOrders { get; set; }
    }
}
