//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListRecipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceListRecipe()
        {
            this.RecipesInOrders = new HashSet<RecipesInOrder>();
        }
    
        public int PriceListID { get; set; }
        public int RecipeID { get; set; }
        public System.TimeSpan TimeForPreparing { get; set; }
        public decimal Price { get; set; }
    
        public virtual PriceList PriceList { get; set; }
        public virtual Recipe Recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecipesInOrder> RecipesInOrders { get; set; }
    }
}
