//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.PriceListRecipes = new HashSet<PriceListRecipe>();
            this.HierararchyInRecipes = new HashSet<HierararchyInRecipe>();
            this.ToppingInRecipes = new HashSet<ToppingInRecipe>();
        }
    
        public int IDRecipe { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool MarkIsWork { get; set; }
        public int ChefID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListRecipe> PriceListRecipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HierararchyInRecipe> HierararchyInRecipes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToppingInRecipe> ToppingInRecipes { get; set; }
    }
}
