//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecipesInOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecipesInOrder()
        {
            this.ItemInRecipes = new HashSet<ItemInRecipe>();
        }
    
        public int IDRecipesInOrders { get; set; }
        public int PriceListID { get; set; }
        public int RecipeID { get; set; }
        public int Hierarchy { get; set; }
        public int OrderID { get; set; }
        public Nullable<bool> MarkCancel { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PriceListRecipe PriceListRecipe { get; set; }
        public virtual HierararchyInRecipe HierararchyInRecipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemInRecipe> ItemInRecipes { get; set; }
    }
}
