//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConfectioneryChain.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffWorkSchedule
    {
        public int IDStaffWorkSchedule { get; set; }
        public int ConfectioneryID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime WorkDay { get; set; }
        public System.TimeSpan TimeBeginWork { get; set; }
        public System.TimeSpan TimeEndWork { get; set; }
        public System.TimeSpan TimeBeginLunch { get; set; }
        public System.TimeSpan TimeEndLunch { get; set; }
    
        public virtual DistributionOfEmployee DistributionOfEmployee { get; set; }
    }
}
